### ISSUE TITLE
WPF 大数据卡顿

### ISSUE THREAD

**Issue by lwqwag** [zenjia/MvvmChart#2]
首先感谢你的伟大项目。
我发现在WPF FX 在选择90000点的大数据下很卡顿，不知道是否有优化的空间，谢谢

**Comment by zenjia** [comment]
谢谢支持！项目设计初衷是MVVM+可定制化+轻量级，如果是大数据或实时数据场景，为了性能，可以使用DrawingVisual或DrawingContext来绘图（具体可以参考Petzold的[文章](https://docs.microsoft.com/en-us/archive/msdn-magazine/2009/march/foundations-writing-more-efficient-itemscontrols)）。不过，这会失去交互性和可定制性，影响到控件的通用性。现在工作主要集中在维护现有的feature上，等代码稳定后再考虑增加对大数据的支持。欢迎提出更多意见和建议。
